import OpenAIService from './OpenAIService';

export interface QuizQuestion {
  question: string;
  options: string[];
  correctAnswer: number;
}

export interface QuizOptions {
  numQuestions?: number;
  difficulty?: 'easy' | 'medium' | 'hard';
  maxTokens?: number;
  temperature?: number;
}

class QuizService extends OpenAIService {
  // For direct text input
  async generateQuiz(content: string, options: QuizOptions = {}): Promise<QuizQuestion[]> {
    try {
      const messages = [{
        role: "system" as const,
        content: "You are a quiz generator that creates multiple choice questions with exactly 4 options each. Return only valid JSON arrays containing questions."
      }, {
        role: "user" as const,
        content: `Create ${options.numQuestions || 5} ${options.difficulty || 'medium'} multiple choice questions about the following content.
          Format as JSON array with "question", "options" (array of 4 choices), and "correctAnswer" (0-3 index) properties.
          Content: ${content}`
      }];

      const response = await this.chatCompletion(messages, {
        maxTokens: options.maxTokens || 2000,
        temperature: options.temperature || 0.7
      });

      const raw = response.choices[0].message.content;
      const questions = this.parseQuestionsFromString(raw);

      return questions;
    } catch (error) {
      console.error('Error generating quiz:', error);
      throw error;
    }
  }

  // For uploaded files
  async generateQuizFromFile(file: File, options: QuizOptions = {}): Promise<QuizQuestion[]> {
    try {
      console.log('QuizService: Starting file processing for:', file.name, file.type);
      
      const prompt = `Create ${options.numQuestions || 5} ${options.difficulty || 'medium'} multiple choice questions from this uploaded document. Format as JSON array with "question", "options" (array of 4 choices), and "correctAnswer" (0-3 index) properties.`;
      
      console.log('QuizService: Calling processUploadedFile with prompt:', prompt);
      
      const result = await this.processUploadedFile(file, prompt, {
        maxTokens: options.maxTokens || 2000,
        temperature: options.temperature || 0.7
      });
      
      const questions = this.parseQuestionsFromString(result);
      console.log('QuizService: Generated questions:', questions.length);
      return questions;
    } catch (error) {
      console.error('QuizService: Error in generateQuizFromFile:', error);
      throw error;
    }
  }

  // Section generated by chatgpt. Was unsure of how to solve my JSON parsing errors. - Cam
  /**
   * Attempt to find and parse a JSON array of questions in a freeform string.
   * This tolerates surrounding explanation text or code fences from the model.
   */
  private parseQuestionsFromString(raw: string): QuizQuestion[] {
    try {
      // First try direct JSON parse (best case)
      const trimmed = raw.trim();
      try {
        const parsed = JSON.parse(trimmed);
        if (Array.isArray(parsed) && this.validateQuestions(parsed)) return parsed;
      } catch {
        // continue to extraction attempts
      }

      // Look for a JSON code block ```json ... ``` or generic ``` ... ```
      const codeFenceMatch = /```(?:json)?([\s\S]*?)```/.exec(raw);
      if (codeFenceMatch && codeFenceMatch[1]) {
        const inside = codeFenceMatch[1].trim();
        try {
          const parsed = JSON.parse(inside);
          if (Array.isArray(parsed) && this.validateQuestions(parsed)) return parsed;
        } catch {
          // fallthrough
        }
      }

      // As a fallback, try to extract the first JSON array found by locating the first '[' and the matching closing ']'
      const firstBracket = raw.indexOf('[');
      if (firstBracket !== -1) {
        // find matching closing bracket by scanning and counting nested brackets
        let depth = 0;
        for (let i = firstBracket; i < raw.length; i++) {
          const ch = raw[i];
          if (ch === '[') depth++;
          else if (ch === ']') depth--;

          if (depth === 0) {
            const candidate = raw.slice(firstBracket, i + 1);
            try {
              const parsed = JSON.parse(candidate);
              if (Array.isArray(parsed) && this.validateQuestions(parsed)) return parsed;
            } catch {
              // continue searching or fail below
            }
            break;
          }
        }
      }

      // If we reach here, we couldn't parse a valid array
      // Provide a helpful error including a short snippet of the model output to help debugging
      const snippet = raw.slice(0, 500).replace(/\n/g, ' ');
      throw new Error(`Unable to parse quiz JSON from model output. Output snippet: "${snippet}"`);
    } catch (err) {
      console.error('QuizService: parseQuestionsFromString error:', err);
      throw err;
    }
  }
  // End of generated code

  private validateQuestions(questions: QuizQuestion[]): boolean {
    return questions.every(q => 
      typeof q.question === 'string' &&
      Array.isArray(q.options) &&
      q.options.length === 4 &&
      typeof q.correctAnswer === 'number' &&
      q.correctAnswer >= 0 &&
      q.correctAnswer <= 3
    );
  }
}

export default new QuizService();